### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by katiejchapman** [nbatta/SZfastMap#1]
fatal: bad object HEAD
Traceback (most recent call last):
  File "testszfm.py", line 3, in <module>
    from pixell import enmap, utils, bunch, pointsrcs
  File "/global/cscratch1/sd/kjc268/pixell/pixell/pointsrcs.py", line 29, in <module>
    from . import utils, enmap, srcsim, wcsutils
ImportError: cannot import name 'srcsim' from 'pixell' (/global/cscratch1/sd/kjc268/pixell/pixell/__init__.py)

srcsim is in pixell/cython while the other imports are in pixell/pixell

**Comment by nbatta** [comment]
Hi @katiejchapman, what version of pixell are you using?
The version that works for me is 0.16.0
you can check this in python by:
>>>import pixell
>>>print (pixell.__version__)
